---
driver_plugin: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: source
    run_list:
      - recipe[exabgp::source]
    attributes:
      exabgp:
        source_version: '3.4'
        hubot:
          enable: true
